"""Constants for the IPBuilding integration."""

DOMAIN = "ipbuilding"
DEFAULT_PORT = 30200

CONF_HOST = "host"
CONF_PORT = "port"

# Device Types
TYPE_RELAY = 1
TYPE_DIMMER = 2
TYPE_DMX = 3
TYPE_ENERGY_COUNTER = 40
TYPE_ENERGY_METER = 41
TYPE_BUTTON = 50
TYPE_TEMPERATURE = 51
TYPE_DETECTOR = 52
TYPE_ANALOG_SENSOR = 53
TYPE_KMI = 54
TYPE_WEATHER_STATION = 55
TYPE_TIME = 56
TYPE_LED = 60
TYPE_ACCESS_READER = 70
TYPE_ACCESS_KEY = 80
TYPE_SPHERE = 100
TYPE_TEMP_SPHERE = 101
TYPE_PROG = 102
TYPE_ACCESS_CONTROL = 103
TYPE_SCRIPT = 150
TYPE_REGIME = 200

# Device Kinds
KIND_LIGHT = 1
KIND_SOCKET = 2
KIND_AUTOMATION = 3
KIND_LOCK = 4
KIND_FAN = 5
KIND_VALVE = 6
KIND_TEMPERATURE = 7
KIND_NOT_APPLICABLE = 8
